### ISSUE TITLE
Specify Camera Requirements

### ISSUE THREAD

**Issue by JonathanWMorris** [Slugbotics/MATE-2023#18]
Acceptance Criteria:

- [ ] Count of cameras is specified
- [ ] Location of cameras is specified
- [ ] Power requirement for cameras specified, how does the camera get power?

Blocking:
https://github.com/Slugbotics/MATE-2023/issues/24

**Comment by juliafishbarbera** [comment]
5 Cameras - 2 narrow angle on front, 1 wide angle per other side 
USB 5v @ 500mA
