### ISSUE TITLE
Specify Lighting Requirements

### ISSUE THREAD

**Issue by JonathanWMorris** [Slugbotics/MATE-2023#19]
Acceptance Criteria:

- [ ] Power requirements for lights documented
- [ ] Light count documented
- [ ] General mounting location of lights documented

Blocking:
https://github.com/Slugbotics/MATE-2023/issues/24

**Comment by juliafishbarbera** [comment]
5 Modules - 30V @ 1A Ea
30V 5A 150W total
Module separate from camera

**Comment by juliafishbarbera** [comment]
After working with integration on power requirements we will be moving to a 2 parallel 3 series configuration for the lights. 
New module specs:
6 Modules 18V each @ 2A max 1.28A nominal

**Comment by JonSheng** [comment]
Is it possible to make the light 12V? For example 3 parallel and 2 series?
