### ISSUE TITLE
Source Enclosure

### ISSUE THREAD

**Issue by JonathanWMorris** [Slugbotics/MATE-2023#26]
Acceptance Criteria:
- [ ] Enclosure Fits all PCBs and Components (Bigger, better)
- [ ] Enclosure is Water Proof
- [ ] Enclosure is affordable and easy to modify

**Comment by CristoeCh** [comment]
11/05 Update: Began salvaging and taking notes on the old enclosure. Measurements on the old enclosure were taken and we have taken into heavy account the necessity of an enclosure large enough. We are beginning the sourcing of a new enclosure making sure it takes into account the IP, size, and shape requirements.
