### ISSUE TITLE
Establish communication with Arduino

### ISSUE THREAD

**Issue by JonathanWMorris** [Slugbotics/MATE-2023#33]
Acceptance Criteria:
- [ ] Laptop can send a string to Arduino in a program
- [ ] Arduino can read the string from Laptop
- [ ] Laptop can send string at a relatively high frequency
- [ ] Data being sent to the Arduino matches the way data is being requested by movement team

Blocked By:
https://github.com/Slugbotics/MATE-2023/issues/10

Blocking:
https://github.com/Slugbotics/MATE-2023/issues/34

**Comment by LoganHaug** [comment]
Completed
